### ISSUE TITLE
Use GitHub Releases instead of ge.tt

### ISSUE THREAD

**Issue by yuchi** [baxtheman/feedback-portlet#1]
:)

**Comment by yuchi** [comment]
Any update on this? (lol)

**Comment by baxtheman** [comment]
dead project by now.. :-(

**Comment by yuchi** [comment]
We’ll revive it! :zap:

**Comment by yuchi** [comment]
![It could work](http://www.fanaticalyankee.com/uploads/5/6/9/8/5698103/396112426.jpg)

**Comment by yuchi** [comment]
(we’re going to revive it soon)

**Comment by yuchi** [comment]
Close for inactivity :)
